app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get '/products/:id', to: 'products#show', as: 'product_page'
  # Nike 
  get "/nike", to: "nike#nikeshoes"

  # JD Sport
  get "/jdsport", to: "jdsport#jdsportshoes"

  # Defines the root path route ("/")
  # root "posts#index"
  root "root#index"
end

app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/app/models/jdsport.rb
class Jdsport < ApplicationRecord
    self.table_name = "jdsport"
end

app/app/models/nike.rb
# app/models/nike.rb
class Nike < ApplicationRecord
    self.table_name = "nike"
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/app/controllers/jdsport_controller.rb
class JdsportController < ApplicationController
    def jdsportshoes
        @jdsportproduct = Jdsport.all
    end
end

app/app/controllers/nike_controller.rb
class NikeController < ApplicationController
    def index
      @nike_products = Nike.all
    end

    def nikeshoes
      @nike_products = Nike.all
    end
end

app/app/controllers/products_controller.rb
# app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @nike_products = Nike.all
    @jdsport_products = Jdsport.all
    @all_products = [@nike_products, @jdsport_products].flatten

    # Find the product with the specified id
    @product = @all_products.find { |product| product.id == params[:id].to_i }

    # Additional logic here if @product needs further customization
  end
end

app/app/controllers/root_controller.rb
class RootController < ApplicationController
    def index
        @nike_products = Nike.all
        @jdsport_products = Jdsport.all
        @all_products = [@nike_products, @jdsport_products].flatten
    end

end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/views/jdsport/jdsportshoes.html.erb
<!-- app/views/nike/index.html.erb -->
<div class="grid grid-cols-3 mt-5 border-black">
  <% @jdsportproduct.each do |product| %>
  <div class="mx-auto mt-10">
      <a href="<%= product_page_path(product) %>">
        <img src="<%= product.image_url %>" width="305" height="350"/>
      </a>
      <a href="<%= product.product_url %>">
        <h1 class="font-kumbh-sans font-bold text-xl text-black-lightbox"><%= product.title %></h1>
      </a>
      <div class="flex justify-between">
        <div>
            <div class="flex">
            <h2 class="text-lg font-bold text-black-lightbox"><%= product.discount_price %></h2>
            <h2 class="bg-pale-orange text-orange font-bold text-center ml-5 text-sm p-1"><%= product.discount_percent %> off</h2>
        </div>
        <s class="text-dark-grayish-blue"><h2 class="text-dark-grayish-blue text-sm"><%= product.original_price %></h2></s>
        </div>
        <div>
            <img src="<%= product.logo %>" width="50" height="50"/>
        </div>
      </div>
  </div>
  <% end %>
</div>

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-F6QHL6V5W0"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-F6QHL6V5W0');
    </script>
    <title>shoehunt</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-O4O9C2aBRnMvK8z5EQrt+OiBS2zF8kB8PyGqZJqKzQ7l4RcwhjT7tT7G+fsSQWUqfqFjGS8i0i9gYQU1Ouj6Q==" crossorigin="anonymous" />


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style>
      .font-kumbh-sans {
        font-family: 'Kumbh Sans', sans-serif;
      }
    </style>
  </head>
  <body class="font-kumbh-sans italic">
    <main>
      <!-- Navigation Bar -->
      <nav class="flex p-4 mx-20 pb-12 mt-6 pr-0 pl-0 border-b border-dark-grayish-blue">
        <div class="container mx-auto flex items-center">
          <!-- Logo -->
          <a href="/" class="text-black-lightbox font-bold text-4xl">shoehunt</a>
        </div>
        <div class="relative inline-block text-left mt-4">
          <div>
            <button type="button" class="inline-flex w-full justify-center gap-x-1.5 rounded-md bg-orange px-3 py-2 text-sm font-semibold text-white shadow-sm ring-1 ring-inset ring-orange hover:bg-pale-orange" id="menu-button" aria-expanded="true" aria-haspopup="true">
              Filters
              <svg class="-mr-1 h-5 w-5 text-white" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd" />
              </svg>
            </button>
          </div>
          <div class="absolute right-0 z-10 mt-2 w-56 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
            <div class="py-1" role="none">
              <!-- Active: "bg-gray-100 text-gray-900", Not Active: "text-gray-700" -->
              <a href="/nike" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">Nike</a>
              <a href="/jdsport" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-1">JD Sports</a>
            </div>
          </div>
        </div>
       
      </nav>
      
      <!-- Main Content -->
      <%= yield %>

      <!-- Footer -->
      <footer class="mt-20 py-8 text-center py-4 text-white font-bold bg-orange">
        <p>&copy; shoehunt 2024. All rights reserved.</p>
      </footer>

    </main>
  </body>
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      const menuButton = document.getElementById('menu-button');
      const dropdownMenu = document.querySelector('.absolute');

      // Hide the dropdown initially
      dropdownMenu.classList.add('hidden');

      menuButton.addEventListener('click', function () {
        dropdownMenu.classList.toggle('hidden');
      });

      // Close the dropdown when clicking outside
      document.addEventListener('click', function (event) {
        const isClickInside = menuButton.contains(event.target) || dropdownMenu.contains(event.target);

        if (!isClickInside) {
          dropdownMenu.classList.add('hidden');
        }
      });
    });
  </script>
</html>

app/app/views/nike/index.html.erb
<!-- app/views/nike/index.html.erb -->
<div class="grid grid-cols-3 mt-5 border-black">
  <% @nike_products.each do |product| %>
  <div class="mx-auto mt-10">
      <a href="#"><img src ="<%= product.image_url %>" width=305 heigh=250/></a>
      <a href="<%= product.product_url %>">
        <h1 class="font-kumbh-sans font-bold text-xl text-black-lightbox"><%= product.title %></h1>
      </a>
      <div class="flex">
        <h2 class="text-lg font-bold text-black-lightbox"><%= product.discount_price %></h2>
        <h2 class="bg-pale-orange text-orange font-bold text-center ml-5 text-sm p-1"><%= product.discount_percent %></h2>
      </div>
      <s class="text-dark-grayish-blue"><h2 class="text-dark-grayish-blue text-sm"><%= product.original_price %></h2></s>
  </div>
  <% end %>
</div>

app/app/views/nike/nikeshoes.html.erb
<!-- app/views/nike/index.html.erb -->
<div class="grid grid-cols-3 mt-5 border-black">
  <% @nike_products.each do |product| %>
  <div class="mx-auto mt-10">
      <a href="<%= product_page_path(product) %>">
        <img src="<%= product.image_url %>" width="305" height="350"/>
      </a>
      <a href="<%= product.product_url %>">
        <h1 class="font-kumbh-sans font-bold text-xl text-black-lightbox"><%= product.title %></h1>
      </a>
      <div class="flex justify-between">
        <div>
            <div class="flex">
            <h2 class="text-lg font-bold text-black-lightbox"><%= product.discount_price %></h2>
            <h2 class="bg-pale-orange text-orange font-bold text-center ml-5 text-sm p-1"><%= product.discount_percent %> off</h2>
        </div>
        <s class="text-dark-grayish-blue"><h2 class="text-dark-grayish-blue text-sm"><%= product.original_price %></h2></s>
        </div>
        <div>
            <img src="<%= product.logo %>" width="50" height="50"/>
        </div>
      </div>
  </div>
  <% end %>
</div>

app/app/views/products/show.html.erb
<!-- app/views/products/show.html.erb -->
<div>
  <div class="w-5/6 flex mt-20 mx-auto">
    <div class="ml-20 rounded-3xl">
      <a href="#">
        <img src="<%= @product.image_url %>" width="1500" class="rounded-2xl"/>
      </a>
    </div>
    <div class="mr-25">
      <div class="font-bold pt-16 pl-14">
        <div class="flex justify-between">
          <h2 class="text-orange">SHOEHUNT</h2>
          <div>
              <img src="<%= @product.logo %>" width="40" height="40"/>
          </div>
        </div>
        <a href="<%= @product.product_url %>">
          <h1 class="font-kumbh-sans font-bold text-2xl pt-3 text-black-lightbox"><%= @product.title %></h1>
        </a>
        <h3 class="text-dark-grayish-blue text-base/6 pt-3 text-n"><%= @product.description %></h3>
        <div class="pt-6">
          <div>
              <div class="flex">
              <h2 class="text-lg text-3xl font-bold text-black-lightbox"><%= @product.discount_price %></h2>
              <h2 class="bg-pale-orange text-xl text-orange font-bold text-center ml-5 text-sm p-1 rounded-lg"><%= @product.discount_percent %></h2>
          </div>
          <s class="text-grayish-blue"><h2 class="text-grayish-blue text-m"><%= @product.original_price %></h2></s>
        </div>
        <div class="pt-6">
          <button class="font-bold bg-light-grayish-blue h-14 w-36 mr-3 rounded-lg transform transition-transform hover:-translate-y-1">wishlist</button>
          <a href="<%= @product.product_url%>"><button class="text-white font-bold bg-orange h-14 w-60 rounded-lg transform transition-transform hover:-translate-y-1">Website</button></a>
        </div>
      </div>
    </div>
  </div>
  <!-- Add more details about the product here -->
</div>

app/app/views/root/index.html.erb
<!-- app/views/nike/index.html.erb -->
<div class="grid grid-cols-3 mt-5 border-dark-grayish-blue">
  <% @all_products .each do |product| %>
  <div class="mx-auto mt-10">
      <a href="<%= product_page_path(product) %>">
        <img src="<%= product.image_url %>" width="305" height="350"/>
      </a>
      <a href="<%= product.product_url %>">
        <h1 class="font-kumbh-sans font-bold text-xl text-black-lightbox"><%= product.title %></h1>
      </a>
      <div class="flex justify-between">
        <div>
            <div class="flex">
            <h2 class="text-lg font-bold text-black-lightbox"><%= product.discount_price %></h2>
            <h2 class="bg-pale-orange text-orange font-bold text-center ml-5 text-sm p-1"><%= product.discount_percent %> off</h2>
        </div>
        <s class="text-dark-grayish-blue"><h2 class="text-dark-grayish-blue text-sm"><%= product.original_price %></h2></s>
        </div>
        <div>
            <img src="<%= product.logo %>" width="50" height="50"/>
        </div>
      </div>
  </div>
  <% end %>
</div>